from pydantic import BaseModel, Field
from typing import List, Dict, Optional


class SubscriptionItem(BaseModel):
    vendor: str = Field(description="Name of the subscription vendor or merchant")
    average_amount: float = Field(description="Average billing amount for this recurring subscription")
    frequency: str = Field(description="Billing frequency: e.g., 'monthly', 'weekly', or 'irregular'")
    last_transaction_date: str = Field(description="The date of the most recent billing charge (DD/MM/YYYY)")


class AnomalyItem(BaseModel):
    transaction_id: str = Field(description="UUID string of the anomalous transaction")
    date: str = Field(description="Date of the anomaly (DD/MM/YYYY)")
    narration: str = Field(description="Raw narration description of the transaction")
    amount: float = Field(description="Debit amount of the anomalous transaction")
    type: str = Field(description="Category type of anomaly: e.g., 'high_value', 'duplicate', 'late_night'")
    reason: str = Field(description="Natural language explanation of why it was flagged")


class AIRecommendationItem(BaseModel):
    title: str = Field(description="Short action-oriented title of the recommendation")
    description: str = Field(description="Detailed explanation of the recommendation and how to execute it")
    impact: str = Field(description="Impact tier: e.g., 'High', 'Medium', 'Low'")
    action_item: str = Field(description="Concrete actionable task for the user to execute")
    target_category: str = Field(description="Target spending category associated with this recommendation")


class AICoachResponse(BaseModel):
    summary: str = Field(description="A concise, highly professional 4-5 sentence summary of the user's spending habits")
    recommendations: List[AIRecommendationItem] = Field(description="Structured financial coaching recommendations")



class StatementInsightsResponse(BaseModel):
    total_income: float = Field(description="Sum of all credit deposits in the statement")
    total_expense: float = Field(description="Sum of all debit withdrawals in the statement")
    net_savings: float = Field(description="Net cash savings flow: Income - Expenses")
    saving_rate: float = Field(description="Savings percentage velocity relative to total income")
    highest_spending_category: str = Field(description="The category name where the user spent the most money")
    category_breakdown: Dict[str, float] = Field(description="Summarized totals spent per transaction category")
    subscriptions: List[SubscriptionItem] = Field(description="Detected recurring subscriptions and bills")
    anomalies: List[AnomalyItem] = Field(description="Detected anomalous, suspicious, or duplicate transactions")
    ai_summary: Optional[str] = Field(None, description="Narrative summary generated by the AI Financial Coach")
    ai_recommendations: List[AIRecommendationItem] = Field(default=[], description="Actionable financial optimizations")


class ChatRequest(BaseModel):
    message: str = Field(description="The user's query or message for the chatbot")
    chat_history: List[Dict[str, str]] = Field(default=[], description="Previous conversation context logs")


class ChatResponse(BaseModel):
    response: str = Field(description="The assistant's grounded response text")
    sources: List[Dict] = Field(default=[], description="List of semantically retrieved transaction source nodes")


class ThesisSection(BaseModel):
    title: str = Field(description="Section title (e.g. 'Cash Flow Dynamics')")
    content: str = Field(description="Detailed narrative analysis of this section")


class FinancialThesisResponse(BaseModel):
    sections: List[ThesisSection] = Field(description="Highly detailed financial analysis sections")



